### ISSUE TITLE
Releasing the code

### ISSUE THREAD

**Issue by C-H-Chien** [kunalchelani/EdgeGaussians#2]
Hi! Thanks for the awesome work! I wonder if there is a time frame of releasing the code? I'd very much like to try it :)

**Comment by kunalchelani** [comment]
Hi! Thanks for the interest. The paper was under review and it has now been accepted to appear at WACV 2025. I will try to release the code by next week.

**Comment by C-H-Chien** [comment]
Congratulations! My paper is also accepted at WACV 2025 and it is highly relevant to your work (3D edge reconstruction). Looking forward to seeing you in WACV next year :)

Will close this issue thread once the code is released. Thanks!

**Comment by jk4011** [comment]
Congratulations!!

**Comment by kunalchelani** [comment]
> Congratulations! My paper is also accepted at WACV 2025 and it is highly relevant to your work (3D edge reconstruction). Looking forward to seeing you in WACV next year :)
> 
> Will close this issue thread once the code is released. Thanks!

Thanks and congrats to you as well! Can you provide a link to your paper as well?

**Comment by kunalchelani** [comment]
I have added an initial commit. Will improve/add functionalities in the next month. Closing the issue for now :)

**Comment by C-H-Chien** [comment]
Hi! Nice meeting you today in WACV! What an amazing work.

I'd love to share my paper and code here in case you are interested in:
[[Paper]](https://openaccess.thecvf.com/content/WACV2025/papers/Zheng_3D_Edge_Sketch_from_Multiview_Images_WACV_2025_paper.pdf) [[Supp]](https://openaccess.thecvf.com/content/WACV2025/supplemental/Zheng_3D_Edge_Sketch_WACV_2025_supplemental.pdf) [[Code]](https://github.com/C-H-Chien/3D_Edge_Sketch)
